# Generated by Django 5.1.4 on 2025-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_member',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('trainer', 'Trainer'), ('member', 'Member'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('manager', 'Manager')], default='member', max_length=15),
        ),
    ]
