# Generated by Django 5.2 on 2025-04-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timing", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField()),
                (
                    "trainer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="trainers.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["timing"],
            },
        ),
    ]
