# Generated by Django 5.2 on 2025-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0003_remove_class_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="name",
            field=models.CharField(default="Gym", max_length=255),
        ),
    ]
